### ISSUE TITLE
basic lesson- words

### ISSUE THREAD

**Issue by hodayadh** [sarafaust/English-learning-website#19]
- [x] open image by click 
- [x] go to specific work by click on button
- [x] enable button of next/prev

**Comment by hodayadh** [comment]
![image](https://user-images.githubusercontent.com/32935554/103159663-cd6c5580-47d4-11eb-8b06-1cfe5d6b7bea.png)

**Comment by hodayadh** [comment]
קצב השיעור אמור להתקדם - להתמלא בירוק בהתאם להתקדמות השיעור

**Comment by sarafaust** [comment]
DONE
