### ISSUE TITLE
other buttons - Main mage

### ISSUE THREAD

**Issue by hodayadh** [sarafaust/English-learning-website#23]
- [x] information button
 - [ ] language button

**Comment by hodayadh** [comment]
![image](https://user-images.githubusercontent.com/32935554/103465420-e54b5880-4d43-11eb-8618-f4a09ab32f87.png)

**Comment by sarafaust** [comment]
information button- done-

**Comment by hodayadh** [comment]
cb0a94fc0494f03cbae046c8c23b9d8025ff0bc1
