### ISSUE TITLE
other buttons - internal lesson page

### ISSUE THREAD

**Issue by hodayadh** [sarafaust/English-learning-website#26]
- [x] cancel button
- [ ] download button
- [x] information button
- [x] print button
- [ ] audio button
- [ ] run button

**Comment by hodayadh** [comment]
![image](https://user-images.githubusercontent.com/32935554/103465847-1168d880-4d48-11eb-95e7-d7c8e8f5c2c4.png)

**Comment by hodayadh** [comment]
![image](https://user-images.githubusercontent.com/32935554/103465859-1fb6f480-4d48-11eb-935b-ec87483f01eb.png)

**Comment by hodayadh** [comment]
- get the data what each button does
- get information about the table of סימני ניקוד

**Comment by sarafaust** [comment]
cancel button : cancel return to home
print - print the page

what download button do?
what play button should  do?

**Comment by sarafaust** [comment]
download button was - minimalize button of desktop SW - so should remove in web version

**Comment by sarafaust** [comment]
run button still have to understand this btn

**Comment by sarafaust** [comment]
commit for implementation 
3b0a1af 
d3e8f9c
